# lightning.pytorch==2.4.0
seed_everything: true
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  max_epochs: 30
  log_every_n_steps: 20
  accumulate_grad_batches: 4
model:
  input_size: 4
  hidden_size: 128
  num_layers: 2
  output_size: 1
data:
  data_file: data/processed/time_series_data.csv
  feature_columns:
    # - year
    - month
    - day_of_week
    - time_of_day
    - total_home_usage
  sequence_length: 288  # The number of time steps in a sequence. 288 = 24 * (60 / 5)
  mins_per_time_step: 5
  batch_size: 300
ckpt_path: null